
// userInfoAction
export const SYN_U_DATA = 'SYN_U_DATA'
export const SUCSSES_EVENT = 'SUCSSES_EVENT'
export const ERROR_EVENT = 'ERROR_EVENT'
export const SHOW_LOADING = 'SHOW_LOADING'
export const UPDATE_ACCES_RULES = 'UPDATE_ACCES_RULES'
export const UPDATE_SIGNATURE_EXIST = 'UPDATE_SIGNATURE_EXIST'
export const UPDATE_SIGNATURE = 'UPDATE_SIGNATURE'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
// UserRelativeInfoAction
export const SYS_RLT_DATA = 'SYS_RLT_DATA'
export const UPDATE_RLT_AVATAR = 'UPDATE_RLT_AVATAR'
// historyTransaction
export const SYS_HIS_DATA = 'SYS_HIS_DATA'
// penddingTransaction
export const SYS_PEN_DATA = 'SYS_PEN_DATA'
// Setting action
export const UPDATE_SOCKETS_ADDRESS = 'UPDATE_SOCKETS_ADDRESS'
export const CONNECTION_STATUS = 'CONNECTION_STATUS'
export const UPDATE_MOMMENT_SCREEN = 'UPDATE_MOMMENT_SCREEN'
export const UPDATE_SOCKETS = 'UPDATE_SOCKETS'
export const UPDATE_VISIBLE_SIGNWRITING = 'UPDATE_VISIBLE_SIGNWRITING'
// Tablet
export const UPDATE_HISTORY_TRANSACTION = 'UPDATE_HISTORY_TRANSACTION'
export const UPDATE_PENDING_TRANSACTION = 'UPDATE_PENDING_TRANSACTION'

export const UPDATE_CONTROL = 'UPDATE_CONTROL'
