// userInfoAction
export const SYN_DATA = 'SYN_DATA'
export const SUCSSES_EVENT = 'SUCSSES_EVENT'
export const ERROR_EVENT = 'ERROR_EVENT'
export const SHOW_LOADING = 'SHOW_LOADING'
export const UPDATE_ACCES_RULES = 'UPDATE_ACCES_RULES'
export const UPDATE_SIGNATURE_EXIST = 'UPDATE_SIGNATURE_EXIST'
export const UPDATE_SIGNATURE = 'UPDATE_SIGNATURE'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
// Setting action
export const UPDATE_SOCKET = 'UPDATE_SOCKET'
export const CONNECTION_STATUS = 'CONNECTION_STATUS'
