const SCREENS = {
  SIGN_WALLETS_SUBMIT: 'SIGN_WALLETS_SUBMIT',
  TAKE_PHOTO_PAGE: 'TAKE_PHOTO_PAGE',
  SETTING_STACK: 'SETTING_STACK',
  SETTING_PAGE: 'SETTING_PAGE',
  USER_INFO_PAGE: 'USER_INFO_PAGE',
  SELECT_SCREEN_PAGE: 'SELECT_SCREEN_PAGE'
}
export default SCREENS
